# Seattle Airbnb Open Data Analys

#### Data Description：
since 2008,guests and hosts have used Airbnb to travel in a more unique, personalized way. As part of the Airbnb Inside initiative, this dataset describes the listing activity of homestays in Seattle, WA.

#### Get Data:
The following Airbnb activity is included in this Seattle dataset:
Listings, including full descriptions and average review score
Reviews, including unique id for each reviewer and detailed comments
Calendar, including listing id and the price and availability for that day

In [334]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [335]:
%matplotlib inline

listings = pd.read_csv('listings.csv')
calendar = pd.read_csv('calendar.csv')
reviews = pd.read_csv('reviews.csv')

In [336]:
print("listings columns:")
print(listings.columns)
print(listings.shape)
print("calendar columns:")
print(calendar.columns)
print(calendar.shape)
print("reviews columns:")
print(reviews.columns)
print(reviews.shape)

listings columns:
Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       'notes', 'transit', 'thumbnail_url', 'medium_url', 'picture_url',
       'xl_picture_url', 'host_id', 'host_url', 'host_name', 'host_since',
       'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'street', 'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'latitude', 'longitude',
       'is_location_exact', 'property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_typ

###### listings columns:

['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       'notes', 'transit', 'thumbnail_url', 'medium_url', 'picture_url',
       'xl_picture_url', 'host_id', 'host_url', 'host_name', 'host_since',
       'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'street', 'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'latitude', 'longitude',
       'is_location_exact', 'property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'square_feet',
       'price', 'weekly_price', 'monthly_price', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
       'maximum_nights', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'first_review', 'last_review', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'requires_license',
       'license', 'jurisdiction_names', 'instant_bookable',
       'cancellation_policy', 'require_guest_profile_picture',
       'require_guest_phone_verification', 'calculated_host_listings_count',
       'reviews_per_month'](3818, 92)


###### calendar columns:
['listing_id', 'date', 'available', 'price']
(1393570, 4)


###### reviews columns:
['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'comments']
(84849, 6)

In [388]:
reviews.sample(2,random_state=42)

listing_id        id        date  reviewer_id reviewer_name  \
41188     6637899  40956769  2015-08-03      5529156        Maggie   
51646     5918259  47360403  2015-09-18      3381323       Melissa   

                                                comments  
41188  Eileen was totally welcoming, a lovely host, o...  
51646  My hubby and I had a wonderful time at Dee's a...

In [338]:
def str_obj_to_number( str_obj):
    number = float( str(str_obj).replace(',', '').split('$')[-1])
    return number

def booleans_to_number( s):
    if s == 'f':
        return 0
    elif s == 't':
        return 1
    return None

In [339]:
print(calendar.columns)
print(calendar.shape)
print(calendar.dtypes)

Index(['listing_id', 'date', 'available', 'price'], dtype='object')
(1393570, 4)
listing_id     int64
date          object
available     object
price         object
dtype: object


In [340]:

calendar['price'] = calendar['price'].apply(str_obj_to_number)
calendar['available'] = calendar['available'].apply(booleans_to_number)
print("calendar.price dtype is :{}".format(calendar['price'].dtype))
print("calendar.available dtype is :{}".format(calendar['available'].dtype))
#calendar[calendar['listing_id'] == 8666707 & calendar['price'].notnull() ]
calendar['price'].notnull().sum()


calendar.price dtype is :float64
calendar.available dtype is :int64


934542

In [341]:
calendar_listing_id_list = calendar['listing_id'].value_counts()
print(calendar_listing_id_list.shape)
print(calendar_listing_id_list.describe())

(3818,)
count    3818.0
mean      365.0
std         0.0
min       365.0
25%       365.0
50%       365.0
75%       365.0
max       365.0
Name: listing_id, dtype: float64


###### we can get some info from calendar data :
- there are 3818 listing ids in Calendar data
- every listing ids have 365 days's record
- some ids are NOT available all year
- some ids are available all year

In [342]:
# we can get some info :
#there are 3818 listing ids
#every listing ids have 365 days's record
#some id is NOT available all year
#some id is available all year
print(calendar[calendar['listing_id']== 777159 ])
print(calendar[calendar['listing_id']== 611500 ])
calendar['listing_id'].unique().shape

        listing_id        date  available  price
832565      777159  2016-01-04          0    NaN
832566      777159  2016-01-05          0    NaN
832567      777159  2016-01-06          0    NaN
832568      777159  2016-01-07          0    NaN
832569      777159  2016-01-08          0    NaN
...            ...         ...        ...    ...
832925      777159  2016-12-29          0    NaN
832926      777159  2016-12-30          0    NaN
832927      777159  2016-12-31          0    NaN
832928      777159  2017-01-01          0    NaN
832929      777159  2017-01-02          0    NaN

[365 rows x 4 columns]
        listing_id        date  available  price
765405      611500  2016-01-04          1  219.0
765406      611500  2016-01-05          1  219.0
765407      611500  2016-01-06          1  219.0
765408      611500  2016-01-07          1  219.0
765409      611500  2016-01-08          1  249.0
...            ...         ...        ...    ...
765765      611500  2016-12-29          1  21

(3818,)

In [343]:
aa_available_days = {}

In [344]:
for i in range(0, calendar_listing_id_list.shape[0]):
    sample = calendar.loc[calendar['listing_id'] == calendar_listing_id_list.index[i] ]
    aa_available_days[calendar_listing_id_list.index[i]] = sample['price'].notnull().sum()

In [345]:
aa_available_days

{6752031: 290,
 7404370: 144,
 1259305: 365,
 4672934: 352,
 10310373: 351,
 479653: 226,
 3251069: 365,
 6400379: 345,
 8597800: 21,
 4841586: 356,
 7710713: 46,
 3155785: 125,
 6949900: 226,
 3646393: 356,
 3870253: 178,
 1252147: 88,
 9280767: 356,
 808134: 162,
 1737244: 365,
 7262358: 338,
 9910189: 0,
 5078244: 356,
 7178490: 358,
 7182584: 251,
 8463726: 348,
 8989807: 27,
 9497431: 135,
 3904056: 365,
 2277640: 0,
 6837338: 38,
 9480029: 365,
 4947002: 362,
 8942678: 53,
 8817033: 77,
 3434459: 321,
 5365612: 296,
 4257097: 365,
 4951079: 365,
 1950446: 167,
 557126: 168,
 8187592: 365,
 4075152: 6,
 8107555: 95,
 4574700: 207,
 7557951: 140,
 8156894: 365,
 4598160: 169,
 8418650: 235,
 10060388: 58,
 3637180: 362,
 9961388: 27,
 3258213: 32,
 461234: 345,
 8472954: 365,
 7620570: 365,
 9387189: 112,
 6783394: 255,
 6807981: 112,
 7024684: 132,
 6776229: 62,
 2027236: 363,
 6512979: 365,
 1806899: 306,
 10299108: 65,
 486829: 185,
 6694276: 365,
 6546748: 345,
 9110560: 87,
 7

In [346]:
print(reviews.columns)
print(reviews.shape)
print(reviews.dtypes)

Index(['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'comments'], dtype='object')
(84849, 6)
listing_id        int64
id                int64
date             object
reviewer_id       int64
reviewer_name    object
comments         object
dtype: object


In [347]:
#are all reviews data's listing_ids  in calendar data's listing_ids?
#answer is yes!
def find_listing_id( raw ):
    if raw.listing_id in calendar_listing_id_list.index:
        return True
    else:
        return False
finding_list = reviews.apply(find_listing_id, axis = 1)
print("Are all reviews data's listing ids in calendar data's listing ids? Answer is : {}".format(finding_list.value_counts().sum() == reviews.shape[0]))

Are all reviews data's listing ids in calendar data's listing ids? Answer is : True


##### Are all reviews data's listing ids in calendar data's listing ids? Answer is : True

In [366]:
listing_data_id_list = listings['id'].unique()
print(len(listing_data_id_list))

3818


In [384]:
#are all listing data's listing_ids  in reviews data's listing_ids?
#answer is yes!
reviews_listing_id_list = reviews['listing_id'].value_counts()
def find_listing_id_2( raw ):
    if raw.id in reviews_listing_id_list.index:
        return True
    else:
        return False
finding_list = listings.apply(find_listing_id_2, axis = 1)
finding_list.describe()
finding_list.value_counts()
#print("Are all listing data's ids in reviews data's listing ids? Answer is : {}".format(finding_list.value_counts().sum() == reviews_listing_id_list.shape[0]))

True     3191
False     627
dtype: int64

##### Are all listing data's ids in review data's listing ids? Answer is : False

In [386]:
reviews_listing_id_list = reviews['listing_id'].value_counts()
missed_listing_id_list = list()
for i in range(0,calendar_listing_id_list.shape[0] ):
    if calendar_listing_id_list.index[i] not in reviews_listing_id_list.index:
        missed_listing_id_list.append(calendar_listing_id_list.index[i] )

missed_listing_id_df = pd.DataFrame({"listing_id":missed_listing_id_list} ,columns=['listing_id'], dtype=np.int64)
print(missed_listing_id_df.shape)


(627, 1)


In [349]:
#reviews[reviews['listing_id'] == 9497431]
for i in range(0,missed_listing_id_df.shape[0]):
    x = missed_listing_id_df['listing_id'][i]
    print("listing id: {} available days: {}".format(x, aa_available_days[x] ) )


listing id: 10310373 available days: 351
listing id: 9280767 available days: 356
listing id: 9910189 available days: 0
listing id: 8989807 available days: 27
listing id: 9497431 available days: 135
listing id: 9480029 available days: 365
listing id: 4075152 available days: 6
listing id: 8107555 available days: 95
listing id: 8156894 available days: 365
listing id: 10060388 available days: 58
listing id: 9961388 available days: 27
listing id: 10299108 available days: 65
listing id: 6694276 available days: 365
listing id: 9288840 available days: 34
listing id: 9999955 available days: 350
listing id: 8503556 available days: 316
listing id: 10234558 available days: 355
listing id: 2729077 available days: 302
listing id: 7501583 available days: 139
listing id: 9921445 available days: 365
listing id: 10124808 available days: 339
listing id: 8674765 available days: 334
listing id: 8555794 available days: 365
listing id: 7984738 available days: 365
listing id: 9435279 available days: 365
listi

In [387]:
print("We get {} listing ids in calendar data but NOT in reviews data".format( missed_listing_id_df.shape[0]))
print("It seems not all ")

We get 627 listing ids in calendar data but NOT in reviews data
Most of these listing datas are available 


In [351]:
print((listings.isnull().sum()/len(listings)).sort_values(ascending=False))

license             1.000000
square_feet         0.974594
monthly_price       0.602672
security_deposit    0.511262
weekly_price        0.473808
                      ...   
accommodates        0.000000
bed_type            0.000000
amenities           0.000000
price               0.000000
id                  0.000000
Length: 92, dtype: float64


In [357]:
#
listings_mis_columns = listings.columns[listings.isnull().sum()/len(listings) > 0.2 ].sort_values(ascending=False)
listings_mis_columns

Index(['weekly_price', 'transit', 'square_feet', 'security_deposit', 'notes',
       'neighborhood_overview', 'monthly_price', 'license',
       'host_acceptance_rate', 'host_about', 'cleaning_fee'],
      dtype='object')

In [358]:
(listings[['weekly_price', 'transit', 'square_feet', 'security_deposit', 'notes',
       'neighborhood_overview', 'monthly_price', 'license',
       'host_acceptance_rate', 'host_about', 'cleaning_fee']].isnull().sum()/len(listings)).sort_values(ascending=False)

license                  1.000000
square_feet              0.974594
monthly_price            0.602672
security_deposit         0.511262
weekly_price             0.473808
notes                    0.420639
neighborhood_overview    0.270299
cleaning_fee             0.269775
transit                  0.244631
host_about               0.224987
host_acceptance_rate     0.202462
dtype: float64

In [360]:
#we should drop some columns,their missing value is greater than 30%
# weekly_price is 
listings[['price','weekly_price', 'transit', 'square_feet', 'security_deposit', 'notes',
       'neighborhood_overview', 'monthly_price', 'license',
       'host_acceptance_rate', 'host_about', 'cleaning_fee']].head(10)

price weekly_price                                            transit  \
0   $85.00          NaN                                                NaN   
1  $150.00    $1,000.00  Convenient bus stops are just down the block, ...   
2  $975.00          NaN  A bus stop is just 2 blocks away.   Easy bus a...   
3  $100.00      $650.00                                                NaN   
4  $450.00          NaN  The nearest public transit bus (D Line) is 2 b...   
5  $120.00      $800.00  The #1 and #2 bus picks up 2-3 blocks away (di...   
6   $80.00      $575.00  The bus goes through the lower Queen Anne neig...   
7   $60.00      $360.00     the "D" line runs out in front of our house .    
8   $90.00      $500.00  Bus stop to downtown directly across the stree...   
9  $150.00    $1,000.00  Convenient bus stops are just down the block, ...   

   square_feet security_deposit  \
0          NaN              NaN   
1          NaN          $100.00   
2          NaN        $1,000.00   
3          NaN              NaN   
4          NaN          $700.00   
5          NaN              NaN   
6          NaN          $150.00   
7          NaN          $150.00   
8          NaN              NaN   
9          NaN          $100.00   

                                               notes  \
0                                                NaN   
1  What's up with the free pillows?  Our home was...   
2  Our house is located just 5 short blocks to To...   
3                                                NaN   
4                                          Belltown    
5  Let me know if you need anything or have sugge...   
6  The room now has a mini frig to keep your favo...   
7  There are three rentals in our back yard . If ...   
8                                                NaN   
9  What's up with the free pillows?  Our home was...   

                               neighborhood_overview monthly_price  license  \
0                                                NaN           NaN      NaN   
1  Queen Anne is a wonderful, truly functional vi...     $3,000.00      NaN   
2  Upper Queen Anne is a charming neighborhood fu...           NaN      NaN   
3                                                NaN     $2,300.00      NaN   
4  We are in the beautiful neighborhood of Queen ...           NaN      NaN   
5  This part of Queen Anne has wonderful views an...           NaN      NaN   
6  Close restaurants, coffee shops and grocery st...           NaN      NaN   
7  We are centrally located between Downtown and ...           NaN      NaN   
8  Walking Score: 92 4 blocks from Kerry Park Fam...     $1,700.00      NaN   
9  Queen Anne is a wonderful, truly functional vi...     $3,000.00      NaN   

  host_acceptance_rate                                         host_about  \
0                 100%  I am an artist, interior designer, and run a s...   
1                 100%  Living east coast/left coast/overseas.  Time i...   
2                 100%  i love living in Seattle.  i grew up in the mi...   
3                  NaN                                                NaN   
4                  NaN  Hi, I live in Seattle, Washington but I'm orig...   
5                  NaN  I've been fortunate to have had many life expe...   
6                 100%  We have lived in the the Queen Anne neighborho...   
7                 100%  I am a carpenter at heart , I love music , I p...   
8                 100%  I'm a 35 year old professional from Seattle, W...   
9                 100%  Living east coast/left coast/overseas.  Time i...   

  cleaning_fee  
0          NaN  
1       $40.00  
2      $300.00  
3          NaN  
4      $125.00  
5       $40.00  
6          NaN  
7       $25.00  
8          NaN  
9       $40.00